---
title: "FAQ"
editor: visual
---

## Frequently Asked Questions

### Does the loop tag harm the fish once it's released?

The loop tag is an external indicator the individual is part of the study. They do not hinder the fish's ability to swim or carry on normal activities post surgery. They're extensively used in mark/recapture studies, where these studies are used for population statistics. In my case, this will be useful for you, the angler, to accurately identify a walleye tied to my study.

These tags are also incredibly useful to determine what proportion of the population is recaptured and where. For instance, if the Emory River is heavily fished due to increased accessibility or popularity by anglers, versus the Clinch River, which might not be as heavily populated with walleye anglers, then I expect more calls about fish coming from the Emory River.

### How long will the study last?

This study will last about a year and a half! I would like to capture movement during two spawning periods: Spring 2025 and Spring 2026, which will help indicate if walleye have a preference of spawning grounds within Watts Bar Reservoir and its tributaries!

### What is the reward?

If an angler catches a walleye and it is deemed not fit to return to the reservoir, you can call me and I will instruct you on how to take out the transmitter and the address to send it to. Once I receive the transmitter in the mail, the angler will receive a \$100 reward.

***However,*** if an angler calls in a captured walleye and **release it back into the reservoir**, the angler's name will be entered in a lottery for the chance to win a \$200 reward at the end of the study.

### How are the walleye breathing during surgery?

The walleye are supplied with a constant steady flow of water over their gills during surgery, so they are stable during the surgery.
